### ISSUE TITLE
Support of python 3.6

### ISSUE THREAD

**Issue by noscode** [grahamgower/demesdraw#31]
Hi @grahamgower,

I noticed that since new version of `demesdraw v0.1.1` Python3.6 is no longer supported. Maybe it is possible to include it back? Some of my projects still use version 3.6 and I would like to use `demesdraw` there.

**Comment by grahamgower** [comment]
Ah, sorry. I released I hadn't actually tested 3.6 (not even in CI), so I just assumed it was broken. I'll add 3.6 to the CI tests and make another release ASAP.

**Comment by noscode** [comment]
Thank you very much @grahamgower, that was really fast!
